### PR TITLE
Utilize s3fs to mount a minio bucket as HD2 - issue 447

### PR DESCRIPTION
**Pull request by ggrig**
Initial implementation of #447

### CODE REVIEW

**Comment by ggrig** [comment]
The PR implements mounting of Minio buckets to HD2 mount point
Both mount and unmount APIs are implemented
Tested in Ubuntu 20.10
Adding this to Alpine (runs in docker-compose) exposed issues

**Comment by ggrig** [comment]
The issue with Alpine was that in order allow s3fs access the fuse the container must be run in privileged mode

**Review by DinisCruz — CHANGES_REQUESTED** [review]
We need to pause this PR, since this solution is not going to work (we can’t give host access to F2F pod)

**Comment by DinisCruz** [comment]
Don’t delete branch

**Pull request closed without merging**
