### PR TITLE
Deleted jupyter

### PR DESCRIPTION
**Pull request by Girish-pingala**

### CODE REVIEW

**Comment by chrisdiao** [comment]
@Girish-pingala could you please: 
1. Add "HOW TO TEST" information in this PR:
    UNIT TEST
    INTEGRATION TEST
    SMOKE TEST

2. Update the DOCUMENTATION - if applicable

**Comment by Girish-pingala** [comment]
Hi Chris,

Testing would be to rescan the repo once it is merged to develop.
________________________________

**Review by pranaysahith — APPROVED** [review]

**Comment by chrisdiao** [comment]
@Girish-pingala , could you please resolve the conflict for this PR?

**Comment by Girish-pingala** [comment]
@chrisdiao conflict has been resolved.

**Pull request merged**
